baseURL = 'https://www.haydenk.blog/'
languageCode = 'en-us'
title = "Hayden's blog"
theme = 'codespace'
buildDrafts = false
summaryLength = 30
disableHugoGeneratorInject = true

[outputFormats]
  [outputFormats.rss]
    mediaType = "application/rss+xml"
    baseName = "feed"
[outputFormats.json]
  mediaType = "application/json"
  baseName = "feed"
  isPlainText = true

[outputs]
  home = ['html', 'rss', 'json']
  page = ['html']
  section = ['html']
  taxonomy = ['html']
  term = ['html']

[pagination]
  pagerSize = 5

[params]
  mainSections = ['blog','atm']
  # Follow the Hugo date/time format reference here: 
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Jan 2 2006"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  # twitter = "https://twitter.com/<your handle>"
  github = "https://github.com/haydenk"
  # email = "mailto:<your email>"
  # mastodon = "https://mastodon.social/@nickname"
  # facebook = "https://facebook.com/<your handle>"
  # gitlab = "https://gitlab.com/<your handle>"
  instagram = "https://instagram.com/imhaydenk"
  linkedin = "https://www.linkedin.com/in/haydenking"
  # youtube = "https://www.youtube.com/channel/<your channel>"
  
  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported: 
  #   "Twitter", "GitHub", "Email", "Mastodon", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconOrder = ["GitHub", "Instagram", "LinkedIn"]

  # Metadata for Twitter cards, defaults to params.twitter
  # twitterSite = "@<your handle>"
  # twitterAuthor = "@<your handle>"

  # Set to true to display page title in table of contents in blog posts.
  showPageTitleInTOC = true

[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  [permalinks.page]
    blog = '/:year/:month/:day/:slug/'
    atm = '/at-the-movies/:year/:month/:day/:slug/'
  [permalinks.section]
    blog = '/blog/'
    atm = '/at-the-movies/'
    linktree = '/quick-links/'

[[menus.main]]
  name = '~/'
  pageRef = '/'
  weight = 10

[[menus.main]]
  name = 'Blog'
  pageRef = 'blog'
  weight = 20

[[menus.main]]
  name = 'At The Movies'
  pageRef = 'atm'
  weight = 30

[[menus.main]]
  name = 'Feed'
  url = '/feed.xml'
  weight = 30
