baseURL = 'https://haydenk.blog/'
languageCode = 'en-us'
title = 'haydenk.blog'
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "My Occasional Scribblings"
  copyright = "Copyright © 2021 Hayden King"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "til"
    name = "til"
    title = "til"
    url = "/til"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/posts/:year/:month/:day/:slug/"
  snippets = "/gists/:year/:slug"

[permalinks.section]
  posts = '/articles/'
  snippets = '/gists/'

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true